version: "3.9"

name: starter-dev

networks:
  appnet:

volumes:
  db_data:
  minio_data:

services:
  db:
    image: mariadb:11
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3
      - "9001:9001" # Console
    volumes:
      - minio_data:/data
    networks:
      - appnet

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    networks:
      - appnet

  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    container_name: api
    environment:
      PORT: 4000
      NODE_ENV: development
      ALLOWED_ORIGINS: http://localhost:8080
      DATABASE_URL: mysql://root:root@db:3306/app_db
      # S3 / MinIO
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET_UPLOADS: uploads
      S3_FORCE_PATH_STYLE: "true"
      S3_SIGNED_URL_EXPIRES: 900
      # OAuth
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      OAUTH_REDIRECT_URI: http://localhost:4000/auth/google/callback
      # JWT
      JWT_ACCESS_SECRET: dev-access-secret
      JWT_REFRESH_SECRET: dev-refresh-secret
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_EXPIRES: 7d
      # SMTP (Mailpit)
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_SECURE: "false"
      SMTP_FROM: "Starter App <no-reply@example.com>"
      # Payments
      PAYMENTS_DEFAULT_CURRENCY: eur
      VAT_FALLBACK_RATE: "0.22"
      STRIPE_SECRET_KEY:
      STRIPE_WEBHOOK_SECRET:
      PAYPAL_CLIENT_ID:
      PAYPAL_CLIENT_SECRET:
      PAYPAL_WEBHOOK_ID:
      PAYPAL_ENV: sandbox
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      mailpit:
        condition: service_started
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - appnet

  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    container_name: web
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - appnet
